import Head from "next/head";
import Container from "../../components/Container";

export default function ArticlePage() {
  return (
    <div className="min-h-screen pt-10">
      <Head>
        <title>Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>article</Container>
    </div>
  );
}
