import Head from "next/head";
import Container from "../../components/Container";
import { getAllPostsId, getPostData } from "../../lib/posts";

export default function PostPage({ postData }) {
  console.log(postData);
  return (
    <div className="min-h-screen pt-10">
      <Head>
        <title>{postData.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>{postData.title}</h1>
      </Container>
    </div>
  );
}

export async function getStaticPaths() {
  const postsId = getAllPostsId();
  const pathList = [];

  for (const postId of postsId) {
    pathList.push({ params: { id: postId } });
  }

  return {
    paths: pathList,
    fallback: true,
  };
}

export async function getStaticProps({ params }) {
  // Add the "await" keyword like this:
  const postData = await getPostData(params.id);

  return {
    props: {
      postData: postData,
    },
  };
}
