import Head from "next/head";
import Image from "next/image";
import Container from "../components/Container";
import indexBackground from "../assets/images/index-background.png";
import Article from "../components/Article";
import Link from "next/link";
import { Separator } from "../components/Separator";
import { Project } from "../components/Project";
import projectImage from "../assets/images/project.png";

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Constant GILLET - Software engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="grid grid-cols-12 gap-6">
          <div className="col-span-6 flex justify-center items-center flex-col">
            <div className="relative w-fit">
              <div className="bg-black dark:bg-white w-full h-full absolute top-[6px] left-[6px]"></div>
              <h1
                className="font-bold dark:text-white text-5xl w-fit py-4 px-6 border border-black dark:border-white bg-white dark:bg-black
                  relative"
              >
                Software
              </h1>
            </div>

            <div className="relative w-fit mt-6 translate-x-[-7px] translate-y-[-7px] rotate-[8deg]">
              <div className="bg-black dark:bg-white w-full h-full absolute top-[6px] left-[6px]"></div>
              <h1
                className="font-bold dark:text-white text-5xl w-fit py-4 px-6 border border-black dark:border-white bg-white dark:bg-black
                  relative"
              >
                Engineer
              </h1>
            </div>
            <div className="flex w-full">
              <p className="font-medium text-2xl max-w-[337px] mt-12">
                This website is about what I have created, what inspires me.
              </p>
            </div>
          </div>
          <div className="col-span-6 flex justify-end">
            <img
              src={indexBackground.src}
              width={384}
              height={485}
              alt="illustration"
            />
          </div>
        </div>
        <div className="w-fit">
          <h2 className={"text-left text-2xl font-bold mt-20 w-fit"}>
            My last articles
          </h2>
          <TitleSeparator />
        </div>
        <section className="mt-14 grid grid-cols-12 gap-6">
          <Article
            title="Books that I like"
            date="07 juillet 2022"
            text="Tu trouveras sur cette page les deniers livres que j’ai lu, en espérant que cela t’inspire aussi."
          />
          <Article
            title="Books that I like"
            date="07 juillet 2022"
            text="Tu trouveras sur cette page les deniers livres que j’ai lu, en espérant que cela t’inspire aussi."
          />
          <Article
            title="Books that I like"
            date="07 juillet 2022"
            text="Tu trouveras sur cette page les deniers livres que j’ai lu, en espérant que cela t’inspire aussi."
          />
        </section>
        <div className="mt-8 flex justify-center">
          <Link href={"/#"}>
            <a title="Article" className="font-bold underline text-center">
              All my articles
            </a>
          </Link>
        </div>
        <Separator className="my-20" />
        <div className="w-fit">
          <h2 className={"text-left text-2xl font-bold mt-4 w-fit"}>
            My projects
          </h2>
          <TitleSeparator />
        </div>
        <section className="mt-14 grid grid-cols-12 gap-8">
          <Project
            title="Upgear, my first airsoft marketplace"
            image={projectImage.src}
          />
          <Project
            title="Upgear, my first airsoft marketplace"
            image={projectImage.src}
          />
          <Project
            title="Upgear, my first airsoft marketplace"
            image={projectImage.src}
          />
        </section>
        <div className="mt-8 flex justify-center">
          <Link href={"/#"}>
            <a title="Article" className="font-bold underline text-center">
              All my projects
            </a>
          </Link>
        </div>
      </Container>
    </div>
  );
}

function TitleSeparator() {
  return (
    <div className="w-[126px] h-[2px] bg-black dark:bg-white mx-auto mt-0.5 after:w-2 after:h-2 after:bg-black dark:after:bg-white relative after:absolute after:left-1/2 after:top-1/2 after:-translate-y-1/2"></div>
  );
}
